trigger:
- main  # Define the branch to trigger the pipeline

pr:  # Define PR triggers if needed
- '*'

pool:
  vmImage: 'ubuntu-latest'  # Use a suitable build agent image (e.g., ubuntu-latest)

variables:
  appName: 'angular-app'  # Replace with your Azure Web App name
  buildPath: '$(Build.SourcesDirectory)/dist'  # Path to Angular build files
stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '20.x'
      
    - task: Npm@1
      displayName: 'NPM Install'
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)'

    - task: Npm@1
      displayName: 'NPM Build'
      inputs:
        command: 'custom'
        workingDir: '$(Build.SourcesDirectory)'
        customCommand: 'run ng build --prod'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(buildPath)/angular-project-demo'
        artifactName: 'drop'
      displayName: 'Publish Build Artifacts'

- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: 'drop'
      displayName: 'Download Build Artifacts'

    #- task: UseDotNet@2
    #  inputs:
     #   packageType: 'sdk'
      #  installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Devops Svc'
        appType: 'webAppLinux'
        appName: 'angular-app'
        package: '$(Pipeline.Workspace)/drop'
